
project_id = "xndzcnzpjdzexmcrotcz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54323

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
